// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.lims;

import java.util.Comparator;
// imports+ 

// imports- 

/**
 * Comparator class is used to sort the ActBean objects.
 */
public class ActComparator implements Comparator
// extends+ 

// extends- 
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for ActComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new ActComparator(ActManager.ACTID, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>ActManager.ID_ACTID
     *   <li>ActManager.ID_CONTRACTID
     *   <li>ActManager.ID_NUM
     *   <li>ActManager.ID_ACTDATE
     *   <li>ActManager.ID_CONTENT
     *   <li>ActManager.ID_SAMPLEAMOUNT
     *   <li>ActManager.ID_REGBYID
     *   <li>ActManager.ID_REGDATE
     *   <li>ActManager.ID_DOCFILE
     *   <li>ActManager.ID_REGIONID
     *   <li>ActManager.ID_RAIONID
     *   <li>ActManager.ID_VILLAGEID
     *   <li>ActManager.ID_BRINGER
     *   <li>ActManager.ID_STAMP
     * </ul>
     */
    public ActComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for ActComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new ActComparator(ActManager.ACTID, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>ActManager.ID_ACTID
     *   <li>ActManager.ID_CONTRACTID
     *   <li>ActManager.ID_NUM
     *   <li>ActManager.ID_ACTDATE
     *   <li>ActManager.ID_CONTENT
     *   <li>ActManager.ID_SAMPLEAMOUNT
     *   <li>ActManager.ID_REGBYID
     *   <li>ActManager.ID_REGDATE
     *   <li>ActManager.ID_DOCFILE
     *   <li>ActManager.ID_REGIONID
     *   <li>ActManager.ID_RAIONID
     *   <li>ActManager.ID_VILLAGEID
     *   <li>ActManager.ID_DELETED
     *   <li>ActManager.ID_BRINGER
     *   <li>ActManager.ID_STAMP
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public ActComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        ActBean b1 = (ActBean)pObj1;
        ActBean b2 = (ActBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case ActManager.ID_ACTID:
                if (b1.getActid() == null && b2.getActid() != null) {
                    iReturn = -1;
                } else if (b1.getActid() == null && b2.getActid() == null) {
                    iReturn = 0;
                } else if (b1.getActid() != null && b2.getActid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getActid().compareTo(b2.getActid());
                }
                break;
            case ActManager.ID_CONTRACTID:
                if (b1.getContractid() == null && b2.getContractid() != null) {
                    iReturn = -1;
                } else if (b1.getContractid() == null && b2.getContractid() == null) {
                    iReturn = 0;
                } else if (b1.getContractid() != null && b2.getContractid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getContractid().compareTo(b2.getContractid());
                }
                break;
            case ActManager.ID_NUM:
                if (b1.getNum() == null && b2.getNum() != null) {
                    iReturn = -1;
                } else if (b1.getNum() == null && b2.getNum() == null) {
                    iReturn = 0;
                } else if (b1.getNum() != null && b2.getNum() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getNum().compareTo(b2.getNum());
                }
                break;
            case ActManager.ID_ACTDATE:
                if (b1.getActdate() == null && b2.getActdate() != null) {
                    iReturn = -1;
                } else if (b1.getActdate() == null && b2.getActdate() == null) {
                    iReturn = 0;
                } else if (b1.getActdate() != null && b2.getActdate() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getActdate().compareTo(b2.getActdate());
                }
                break;
            case ActManager.ID_CONTENT:
                if (b1.getContent() == null && b2.getContent() != null) {
                    iReturn = -1;
                } else if (b1.getContent() == null && b2.getContent() == null) {
                    iReturn = 0;
                } else if (b1.getContent() != null && b2.getContent() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getContent().compareTo(b2.getContent());
                }
                break;
            case ActManager.ID_SAMPLEAMOUNT:
                if (b1.getSampleamount() == null && b2.getSampleamount() != null) {
                    iReturn = -1;
                } else if (b1.getSampleamount() == null && b2.getSampleamount() == null) {
                    iReturn = 0;
                } else if (b1.getSampleamount() != null && b2.getSampleamount() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getSampleamount().compareTo(b2.getSampleamount());
                }
                break;
            case ActManager.ID_REGBYID:
                if (b1.getRegbyid() == null && b2.getRegbyid() != null) {
                    iReturn = -1;
                } else if (b1.getRegbyid() == null && b2.getRegbyid() == null) {
                    iReturn = 0;
                } else if (b1.getRegbyid() != null && b2.getRegbyid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getRegbyid().compareTo(b2.getRegbyid());
                }
                break;
            case ActManager.ID_REGDATE:
                if (b1.getRegdate() == null && b2.getRegdate() != null) {
                    iReturn = -1;
                } else if (b1.getRegdate() == null && b2.getRegdate() == null) {
                    iReturn = 0;
                } else if (b1.getRegdate() != null && b2.getRegdate() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getRegdate().compareTo(b2.getRegdate());
                }
                break;
            case ActManager.ID_DOCFILE:
                if (b1.getDocfile() == null && b2.getDocfile() != null) {
                    iReturn = -1;
                } else if (b1.getDocfile() == null && b2.getDocfile() == null) {
                    iReturn = 0;
                } else if (b1.getDocfile() != null && b2.getDocfile() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getDocfile().compareTo(b2.getDocfile());
                }
                break;
            case ActManager.ID_REGIONID:
                if (b1.getRegionid() == null && b2.getRegionid() != null) {
                    iReturn = -1;
                } else if (b1.getRegionid() == null && b2.getRegionid() == null) {
                    iReturn = 0;
                } else if (b1.getRegionid() != null && b2.getRegionid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getRegionid().compareTo(b2.getRegionid());
                }
                break;
            case ActManager.ID_RAIONID:
                if (b1.getRaionid() == null && b2.getRaionid() != null) {
                    iReturn = -1;
                } else if (b1.getRaionid() == null && b2.getRaionid() == null) {
                    iReturn = 0;
                } else if (b1.getRaionid() != null && b2.getRaionid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getRaionid().compareTo(b2.getRaionid());
                }
                break;
            case ActManager.ID_VILLAGEID:
                if (b1.getVillageid() == null && b2.getVillageid() != null) {
                    iReturn = -1;
                } else if (b1.getVillageid() == null && b2.getVillageid() == null) {
                    iReturn = 0;
                } else if (b1.getVillageid() != null && b2.getVillageid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getVillageid().compareTo(b2.getVillageid());
                }
                break;
            case ActManager.ID_BRINGER:
                if (b1.getBringer() == null && b2.getBringer() != null) {
                    iReturn = -1;
                } else if (b1.getBringer() == null && b2.getBringer() == null) {
                    iReturn = 0;
                } else if (b1.getBringer() != null && b2.getBringer() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getBringer().compareTo(b2.getBringer());
                }
                break;
            case ActManager.ID_STAMP:
                if (b1.getStamp() == null && b2.getStamp() != null) {
                    iReturn = -1;
                } else if (b1.getStamp() == null && b2.getStamp() == null) {
                    iReturn = 0;
                } else if (b1.getStamp() != null && b2.getStamp() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getStamp().compareTo(b2.getStamp());
                }
                break;
            default: 
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }
// class+ 

// class- 
}
