// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.lims;

import java.util.Comparator;
// imports+ 

// imports- 

/**
 * Comparator class is used to sort the AppealBean objects.
 */
public class AppealComparator implements Comparator
// extends+ 

// extends- 
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for AppealComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new AppealComparator(AppealManager.APPEALID, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>AppealManager.ID_APPEALID
     *   <li>AppealManager.ID_CONTRACTID
     *   <li>AppealManager.ID_NUM
     *   <li>AppealManager.ID_APPEALDATE
     *   <li>AppealManager.ID_PATH
     *   <li>AppealManager.ID_SAMPLENUM
     *   <li>AppealManager.ID_REGBYID
     *   <li>AppealManager.ID_REGDATE
     *   <li>AppealManager.ID_REGIONID
     *   <li>AppealManager.ID_RAIONID
     *   <li>AppealManager.ID_VILLAGEID
     *   <li>AppealManager.ID_BRINGER
     *   <li>AppealManager.ID_STAMP
     * </ul>
     */
    public AppealComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for AppealComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new AppealComparator(AppealManager.APPEALID, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>AppealManager.ID_APPEALID
     *   <li>AppealManager.ID_CONTRACTID
     *   <li>AppealManager.ID_NUM
     *   <li>AppealManager.ID_APPEALDATE
     *   <li>AppealManager.ID_PATH
     *   <li>AppealManager.ID_SAMPLENUM
     *   <li>AppealManager.ID_REGBYID
     *   <li>AppealManager.ID_REGDATE
     *   <li>AppealManager.ID_REGIONID
     *   <li>AppealManager.ID_RAIONID
     *   <li>AppealManager.ID_VILLAGEID
     *   <li>AppealManager.ID_DELETED
     *   <li>AppealManager.ID_BRINGER
     *   <li>AppealManager.ID_STAMP
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public AppealComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        AppealBean b1 = (AppealBean)pObj1;
        AppealBean b2 = (AppealBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case AppealManager.ID_APPEALID:
                if (b1.getAppealid() == null && b2.getAppealid() != null) {
                    iReturn = -1;
                } else if (b1.getAppealid() == null && b2.getAppealid() == null) {
                    iReturn = 0;
                } else if (b1.getAppealid() != null && b2.getAppealid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getAppealid().compareTo(b2.getAppealid());
                }
                break;
            case AppealManager.ID_CONTRACTID:
                if (b1.getContractid() == null && b2.getContractid() != null) {
                    iReturn = -1;
                } else if (b1.getContractid() == null && b2.getContractid() == null) {
                    iReturn = 0;
                } else if (b1.getContractid() != null && b2.getContractid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getContractid().compareTo(b2.getContractid());
                }
                break;
            case AppealManager.ID_NUM:
                if (b1.getNum() == null && b2.getNum() != null) {
                    iReturn = -1;
                } else if (b1.getNum() == null && b2.getNum() == null) {
                    iReturn = 0;
                } else if (b1.getNum() != null && b2.getNum() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getNum().compareTo(b2.getNum());
                }
                break;
            case AppealManager.ID_APPEALDATE:
                if (b1.getAppealdate() == null && b2.getAppealdate() != null) {
                    iReturn = -1;
                } else if (b1.getAppealdate() == null && b2.getAppealdate() == null) {
                    iReturn = 0;
                } else if (b1.getAppealdate() != null && b2.getAppealdate() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getAppealdate().compareTo(b2.getAppealdate());
                }
                break;
            case AppealManager.ID_PATH:
                if (b1.getPath() == null && b2.getPath() != null) {
                    iReturn = -1;
                } else if (b1.getPath() == null && b2.getPath() == null) {
                    iReturn = 0;
                } else if (b1.getPath() != null && b2.getPath() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getPath().compareTo(b2.getPath());
                }
                break;
            case AppealManager.ID_SAMPLENUM:
                if (b1.getSamplenum() == null && b2.getSamplenum() != null) {
                    iReturn = -1;
                } else if (b1.getSamplenum() == null && b2.getSamplenum() == null) {
                    iReturn = 0;
                } else if (b1.getSamplenum() != null && b2.getSamplenum() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getSamplenum().compareTo(b2.getSamplenum());
                }
                break;
            case AppealManager.ID_REGBYID:
                if (b1.getRegbyid() == null && b2.getRegbyid() != null) {
                    iReturn = -1;
                } else if (b1.getRegbyid() == null && b2.getRegbyid() == null) {
                    iReturn = 0;
                } else if (b1.getRegbyid() != null && b2.getRegbyid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getRegbyid().compareTo(b2.getRegbyid());
                }
                break;
            case AppealManager.ID_REGDATE:
                if (b1.getRegdate() == null && b2.getRegdate() != null) {
                    iReturn = -1;
                } else if (b1.getRegdate() == null && b2.getRegdate() == null) {
                    iReturn = 0;
                } else if (b1.getRegdate() != null && b2.getRegdate() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getRegdate().compareTo(b2.getRegdate());
                }
                break;
            case AppealManager.ID_REGIONID:
                if (b1.getRegionid() == null && b2.getRegionid() != null) {
                    iReturn = -1;
                } else if (b1.getRegionid() == null && b2.getRegionid() == null) {
                    iReturn = 0;
                } else if (b1.getRegionid() != null && b2.getRegionid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getRegionid().compareTo(b2.getRegionid());
                }
                break;
            case AppealManager.ID_RAIONID:
                if (b1.getRaionid() == null && b2.getRaionid() != null) {
                    iReturn = -1;
                } else if (b1.getRaionid() == null && b2.getRaionid() == null) {
                    iReturn = 0;
                } else if (b1.getRaionid() != null && b2.getRaionid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getRaionid().compareTo(b2.getRaionid());
                }
                break;
            case AppealManager.ID_VILLAGEID:
                if (b1.getVillageid() == null && b2.getVillageid() != null) {
                    iReturn = -1;
                } else if (b1.getVillageid() == null && b2.getVillageid() == null) {
                    iReturn = 0;
                } else if (b1.getVillageid() != null && b2.getVillageid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getVillageid().compareTo(b2.getVillageid());
                }
                break;
            case AppealManager.ID_BRINGER:
                if (b1.getBringer() == null && b2.getBringer() != null) {
                    iReturn = -1;
                } else if (b1.getBringer() == null && b2.getBringer() == null) {
                    iReturn = 0;
                } else if (b1.getBringer() != null && b2.getBringer() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getBringer().compareTo(b2.getBringer());
                }
                break;
            case AppealManager.ID_STAMP:
                if (b1.getStamp() == null && b2.getStamp() != null) {
                    iReturn = -1;
                } else if (b1.getStamp() == null && b2.getStamp() == null) {
                    iReturn = 0;
                } else if (b1.getStamp() != null && b2.getStamp() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getStamp().compareTo(b2.getStamp());
                }
                break;
            default: 
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }
// class+ 

// class- 
}
