// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.lims;

import java.util.Comparator;
// imports+ 

// imports- 

/**
 * Comparator class is used to sort the CompanyBean objects.
 */
public class CompanyComparator implements Comparator
// extends+ 

// extends- 
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for CompanyComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new CompanyComparator(CompanyManager.COMPANYID, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>CompanyManager.ID_COMPANYID
     *   <li>CompanyManager.ID_NAME
     *   <li>CompanyManager.ID_LOGO
     *   <li>CompanyManager.ID_URL
     * </ul>
     */
    public CompanyComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for CompanyComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new CompanyComparator(CompanyManager.COMPANYID, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>CompanyManager.ID_COMPANYID
     *   <li>CompanyManager.ID_NAME
     *   <li>CompanyManager.ID_LOGO
     *   <li>CompanyManager.ID_URL
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public CompanyComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        CompanyBean b1 = (CompanyBean)pObj1;
        CompanyBean b2 = (CompanyBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case CompanyManager.ID_COMPANYID:
                if (b1.getCompanyid() == null && b2.getCompanyid() != null) {
                    iReturn = -1;
                } else if (b1.getCompanyid() == null && b2.getCompanyid() == null) {
                    iReturn = 0;
                } else if (b1.getCompanyid() != null && b2.getCompanyid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getCompanyid().compareTo(b2.getCompanyid());
                }
                break;
            case CompanyManager.ID_NAME:
                if (b1.getName() == null && b2.getName() != null) {
                    iReturn = -1;
                } else if (b1.getName() == null && b2.getName() == null) {
                    iReturn = 0;
                } else if (b1.getName() != null && b2.getName() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getName().compareTo(b2.getName());
                }
                break;
            case CompanyManager.ID_LOGO:
                if (b1.getLogo() == null && b2.getLogo() != null) {
                    iReturn = -1;
                } else if (b1.getLogo() == null && b2.getLogo() == null) {
                    iReturn = 0;
                } else if (b1.getLogo() != null && b2.getLogo() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getLogo().compareTo(b2.getLogo());
                }
                break;
            case CompanyManager.ID_URL:
                if (b1.getUrl() == null && b2.getUrl() != null) {
                    iReturn = -1;
                } else if (b1.getUrl() == null && b2.getUrl() == null) {
                    iReturn = 0;
                } else if (b1.getUrl() != null && b2.getUrl() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getUrl().compareTo(b2.getUrl());
                }
                break;
            default: 
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }
// class+ 

// class- 
}
