// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.lims;

import java.sql.SQLException;
// imports+ 

// imports- 


/**
 * Listener that is notified of contractsampletype table changes.
 */
public interface ContractsampletypeListener
// extends+ 

// extends- 
{
    /**
     * Invoked just before inserting a ContractsampletypeBean record into the database.
     *
     * @param pObject the ContractsampletypeBean that is about to be inserted
     */
    public void beforeInsert(ContractsampletypeBean pObject) throws SQLException;


    /**
     * Invoked just after a ContractsampletypeBean record is inserted in the database.
     *
     * @param pObject the ContractsampletypeBean that was just inserted
     */
    public void afterInsert(ContractsampletypeBean pObject) throws SQLException;


    /**
     * Invoked just before updating a ContractsampletypeBean record in the database.
     *
     * @param pObject the ContractsampletypeBean that is about to be updated
     */
    public void beforeUpdate(ContractsampletypeBean pObject) throws SQLException;


    /**
     * Invoked just after updating a ContractsampletypeBean record in the database.
     *
     * @param pObject the ContractsampletypeBean that was just updated
     */
    public void afterUpdate(ContractsampletypeBean pObject) throws SQLException;


// class+ 

// class- 
}
