// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.lims;

import java.sql.SQLException;
// imports+ 

// imports- 


/**
 * Listener that is notified of institution table changes.
 */
public interface InstitutionListener
// extends+ 

// extends- 
{
    /**
     * Invoked just before inserting a InstitutionBean record into the database.
     *
     * @param pObject the InstitutionBean that is about to be inserted
     */
    public void beforeInsert(InstitutionBean pObject) throws SQLException;


    /**
     * Invoked just after a InstitutionBean record is inserted in the database.
     *
     * @param pObject the InstitutionBean that was just inserted
     */
    public void afterInsert(InstitutionBean pObject) throws SQLException;


    /**
     * Invoked just before updating a InstitutionBean record in the database.
     *
     * @param pObject the InstitutionBean that is about to be updated
     */
    public void beforeUpdate(InstitutionBean pObject) throws SQLException;


    /**
     * Invoked just after updating a InstitutionBean record in the database.
     *
     * @param pObject the InstitutionBean that was just updated
     */
    public void afterUpdate(InstitutionBean pObject) throws SQLException;


// class+ 

// class- 
}
