// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.lims;

import java.sql.SQLException;
// imports+ 

// imports- 


/**
 * Listener that is notified of labtestprod table changes.
 */
public interface LabtestprodListener
// extends+ 

// extends- 
{
    /**
     * Invoked just before inserting a LabtestprodBean record into the database.
     *
     * @param pObject the LabtestprodBean that is about to be inserted
     */
    public void beforeInsert(LabtestprodBean pObject) throws SQLException;


    /**
     * Invoked just after a LabtestprodBean record is inserted in the database.
     *
     * @param pObject the LabtestprodBean that was just inserted
     */
    public void afterInsert(LabtestprodBean pObject) throws SQLException;


    /**
     * Invoked just before updating a LabtestprodBean record in the database.
     *
     * @param pObject the LabtestprodBean that is about to be updated
     */
    public void beforeUpdate(LabtestprodBean pObject) throws SQLException;


    /**
     * Invoked just after updating a LabtestprodBean record in the database.
     *
     * @param pObject the LabtestprodBean that was just updated
     */
    public void afterUpdate(LabtestprodBean pObject) throws SQLException;


// class+ 

// class- 
}
