// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.lims;

import java.sql.SQLException;
// imports+ 

// imports- 


/**
 * Listener that is notified of postponeitem table changes.
 */
public interface PostponeitemListener
// extends+ 

// extends- 
{
    /**
     * Invoked just before inserting a PostponeitemBean record into the database.
     *
     * @param pObject the PostponeitemBean that is about to be inserted
     */
    public void beforeInsert(PostponeitemBean pObject) throws SQLException;


    /**
     * Invoked just after a PostponeitemBean record is inserted in the database.
     *
     * @param pObject the PostponeitemBean that was just inserted
     */
    public void afterInsert(PostponeitemBean pObject) throws SQLException;


    /**
     * Invoked just before updating a PostponeitemBean record in the database.
     *
     * @param pObject the PostponeitemBean that is about to be updated
     */
    public void beforeUpdate(PostponeitemBean pObject) throws SQLException;


    /**
     * Invoked just after updating a PostponeitemBean record in the database.
     *
     * @param pObject the PostponeitemBean that was just updated
     */
    public void afterUpdate(PostponeitemBean pObject) throws SQLException;


// class+ 

// class- 
}
