// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.lims;

import java.sql.SQLException;
// imports+ 

// imports- 


/**
 * Listener that is notified of productunit table changes.
 */
public interface ProductunitListener
// extends+ 

// extends- 
{
    /**
     * Invoked just before inserting a ProductunitBean record into the database.
     *
     * @param pObject the ProductunitBean that is about to be inserted
     */
    public void beforeInsert(ProductunitBean pObject) throws SQLException;


    /**
     * Invoked just after a ProductunitBean record is inserted in the database.
     *
     * @param pObject the ProductunitBean that was just inserted
     */
    public void afterInsert(ProductunitBean pObject) throws SQLException;


    /**
     * Invoked just before updating a ProductunitBean record in the database.
     *
     * @param pObject the ProductunitBean that is about to be updated
     */
    public void beforeUpdate(ProductunitBean pObject) throws SQLException;


    /**
     * Invoked just after updating a ProductunitBean record in the database.
     *
     * @param pObject the ProductunitBean that was just updated
     */
    public void afterUpdate(ProductunitBean pObject) throws SQLException;


// class+ 

// class- 
}
