// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.lims;

import java.sql.SQLException;
// imports+ 

// imports- 


/**
 * Listener that is notified of sampleitemtest table changes.
 */
public interface SampleitemtestListener
// extends+ 

// extends- 
{
    /**
     * Invoked just before inserting a SampleitemtestBean record into the database.
     *
     * @param pObject the SampleitemtestBean that is about to be inserted
     */
    public void beforeInsert(SampleitemtestBean pObject) throws SQLException;


    /**
     * Invoked just after a SampleitemtestBean record is inserted in the database.
     *
     * @param pObject the SampleitemtestBean that was just inserted
     */
    public void afterInsert(SampleitemtestBean pObject) throws SQLException;


    /**
     * Invoked just before updating a SampleitemtestBean record in the database.
     *
     * @param pObject the SampleitemtestBean that is about to be updated
     */
    public void beforeUpdate(SampleitemtestBean pObject) throws SQLException;


    /**
     * Invoked just after updating a SampleitemtestBean record in the database.
     *
     * @param pObject the SampleitemtestBean that was just updated
     */
    public void afterUpdate(SampleitemtestBean pObject) throws SQLException;


// class+ 

// class- 
}
