// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.lims;

import java.sql.SQLException;
// imports+ 

// imports- 


/**
 * Listener that is notified of sampleitemreseach table changes.
 */
public interface SampleitemreseachListener
// extends+ 

// extends- 
{
    /**
     * Invoked just before inserting a SampleitemreseachBean record into the database.
     *
     * @param pObject the SampleitemreseachBean that is about to be inserted
     */
    public void beforeInsert(SampleitemreseachBean pObject) throws SQLException;


    /**
     * Invoked just after a SampleitemreseachBean record is inserted in the database.
     *
     * @param pObject the SampleitemreseachBean that was just inserted
     */
    public void afterInsert(SampleitemreseachBean pObject) throws SQLException;


    /**
     * Invoked just before updating a SampleitemreseachBean record in the database.
     *
     * @param pObject the SampleitemreseachBean that is about to be updated
     */
    public void beforeUpdate(SampleitemreseachBean pObject) throws SQLException;


    /**
     * Invoked just after updating a SampleitemreseachBean record in the database.
     *
     * @param pObject the SampleitemreseachBean that was just updated
     */
    public void afterUpdate(SampleitemreseachBean pObject) throws SQLException;


// class+ 

// class- 
}
