// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.lims;

import java.util.Comparator;
// imports+ 

// imports- 

/**
 * Comparator class is used to sort the StockBean objects.
 */
public class StockComparator implements Comparator
// extends+ 

// extends- 
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for StockComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new StockComparator(StockManager.STOCKID, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>StockManager.ID_STOCKID
     *   <li>StockManager.ID_PARENTID
     *   <li>StockManager.ID_NAME
     *   <li>StockManager.ID_COMPANYID
     * </ul>
     */
    public StockComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for StockComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new StockComparator(StockManager.STOCKID, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>StockManager.ID_STOCKID
     *   <li>StockManager.ID_PARENTID
     *   <li>StockManager.ID_NAME
     *   <li>StockManager.ID_COMPANYID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public StockComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        StockBean b1 = (StockBean)pObj1;
        StockBean b2 = (StockBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case StockManager.ID_STOCKID:
                if (b1.getStockid() == null && b2.getStockid() != null) {
                    iReturn = -1;
                } else if (b1.getStockid() == null && b2.getStockid() == null) {
                    iReturn = 0;
                } else if (b1.getStockid() != null && b2.getStockid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getStockid().compareTo(b2.getStockid());
                }
                break;
            case StockManager.ID_PARENTID:
                if (b1.getParentid() == null && b2.getParentid() != null) {
                    iReturn = -1;
                } else if (b1.getParentid() == null && b2.getParentid() == null) {
                    iReturn = 0;
                } else if (b1.getParentid() != null && b2.getParentid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getParentid().compareTo(b2.getParentid());
                }
                break;
            case StockManager.ID_NAME:
                if (b1.getName() == null && b2.getName() != null) {
                    iReturn = -1;
                } else if (b1.getName() == null && b2.getName() == null) {
                    iReturn = 0;
                } else if (b1.getName() != null && b2.getName() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getName().compareTo(b2.getName());
                }
                break;
            case StockManager.ID_COMPANYID:
                if (b1.getCompanyid() == null && b2.getCompanyid() != null) {
                    iReturn = -1;
                } else if (b1.getCompanyid() == null && b2.getCompanyid() == null) {
                    iReturn = 0;
                } else if (b1.getCompanyid() != null && b2.getCompanyid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getCompanyid().compareTo(b2.getCompanyid());
                }
                break;
            default: 
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }
// class+ 

// class- 
}
