// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.lims;

import java.util.Comparator;
// imports+ 

// imports- 

/**
 * Comparator class is used to sort the TestgroupBean objects.
 */
public class TestgroupComparator implements Comparator
// extends+ 

// extends- 
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for TestgroupComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new TestgroupComparator(TestgroupManager.TESTGROUPID, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>TestgroupManager.ID_TESTGROUPID
     *   <li>TestgroupManager.ID_LABTESTID
     * </ul>
     */
    public TestgroupComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for TestgroupComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new TestgroupComparator(TestgroupManager.TESTGROUPID, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>TestgroupManager.ID_TESTGROUPID
     *   <li>TestgroupManager.ID_LABTESTID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public TestgroupComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        TestgroupBean b1 = (TestgroupBean)pObj1;
        TestgroupBean b2 = (TestgroupBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case TestgroupManager.ID_TESTGROUPID:
                if (b1.getTestgroupid() == null && b2.getTestgroupid() != null) {
                    iReturn = -1;
                } else if (b1.getTestgroupid() == null && b2.getTestgroupid() == null) {
                    iReturn = 0;
                } else if (b1.getTestgroupid() != null && b2.getTestgroupid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getTestgroupid().compareTo(b2.getTestgroupid());
                }
                break;
            case TestgroupManager.ID_LABTESTID:
                if (b1.getLabtestid() == null && b2.getLabtestid() != null) {
                    iReturn = -1;
                } else if (b1.getLabtestid() == null && b2.getLabtestid() == null) {
                    iReturn = 0;
                } else if (b1.getLabtestid() != null && b2.getLabtestid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getLabtestid().compareTo(b2.getLabtestid());
                }
                break;
            default: 
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }
// class+ 

// class- 
}
